#!/usr/bin/env python3
"""
Mega-Sena vs CRNG vs NumPy PRNG — Comprehensive Statistical Analysis
=====================================================================

Analyzes ~2989 real Mega-Sena draws and compares their statistical
fingerprint against synthetic lottery draws generated by CRNG and NumPy.

Metrics tested:
1. Frequency distribution (Chi-squared uniformity test)
2. Permutation Entropy (PE) — ordinal complexity
3. Serial correlation (lag-1 autocorrelation)
4. Gap analysis (average gap between appearances)
5. Sum distribution (sum of 6 balls per draw)
6. Consecutive numbers frequency
7. Hot/cold number patterns (temporal clustering)
8. Hurst exponent (long-range dependence)
9. Runs test (randomness of sequences)
10. Birthday spacing test
"""

import numpy as np
import openpyxl
from collections import Counter, defaultdict
from itertools import permutations
from math import factorial, log, sqrt
import sys
import os

# Add parent directory to path for crng import
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from crng import ContingencyRNG

# ─── Data Loading ───────────────────────────────────────────────

def load_mega_sena(path):
    """Load Mega-Sena draws from Excel file."""
    wb = openpyxl.load_workbook(path)
    ws = wb.active

    draws = []
    for row in ws.iter_rows(min_row=2, max_col=8, values_only=True):
        concurso = row[0]
        if concurso is None:
            break
        # Columns: Concurso(0), Data(1), Bola1(2)..Bola6(7)
        bolas = row[2:8]
        balls = [int(b) for b in bolas if b is not None]
        if len(balls) == 6:
            draws.append(sorted(balls))

    wb.close()
    print(f"  Loaded {len(draws)} Mega-Sena draws")
    return draws


def generate_prng_draws(n_draws, seed=42):
    """Generate synthetic lottery draws using NumPy PRNG."""
    rng = np.random.default_rng(seed)
    draws = []
    for _ in range(n_draws):
        balls = sorted(rng.choice(range(1, 61), size=6, replace=False).tolist())
        draws.append(balls)
    return draws


def generate_crng_draws(n_draws, seed=42):
    """Generate synthetic lottery draws using CRNG."""
    crng = ContingencyRNG(seed=seed, target_kurtosis=6.0)
    draws = []
    for _ in range(n_draws):
        balls = set()
        while len(balls) < 6:
            val = crng.next()
            # Map CRNG output (roughly 0-centered) to 1-60
            ball = int(abs(val * 15) % 60) + 1
            balls.add(ball)
        draws.append(sorted(balls))
    return draws


# ─── Statistical Metrics ────────────────────────────────────────

def frequency_chi_squared(draws, n_balls=60):
    """Chi-squared test for uniformity of ball frequencies."""
    counts = Counter()
    total_balls = 0
    for draw in draws:
        for b in draw:
            counts[b] += 1
            total_balls += 1

    expected = total_balls / n_balls
    chi2 = sum((counts.get(i, 0) - expected) ** 2 / expected for i in range(1, n_balls + 1))

    # df = 59, critical value at 0.05 = 79.08
    return chi2


def permutation_entropy(sequence, order=3):
    """Permutation Entropy — measures ordinal pattern complexity."""
    n = len(sequence)
    if n < order + 1:
        return 0.0

    # Count ordinal patterns
    pattern_counts = Counter()
    for i in range(n - order + 1):
        window = sequence[i:i + order]
        # Get the rank pattern
        ranked = tuple(sorted(range(order), key=lambda k: window[k]))
        pattern_counts[ranked] += 1

    total = sum(pattern_counts.values())
    max_patterns = factorial(order)

    # Shannon entropy normalized by max
    entropy = 0.0
    for count in pattern_counts.values():
        p = count / total
        if p > 0:
            entropy -= p * log(p)

    max_entropy = log(max_patterns)
    return entropy / max_entropy if max_entropy > 0 else 0.0


def serial_correlation(sequence, lag=1):
    """Lag-k serial correlation coefficient."""
    n = len(sequence)
    if n < lag + 2:
        return 0.0

    mean = np.mean(sequence)
    var = np.var(sequence)
    if var == 0:
        return 0.0

    corr = np.mean((np.array(sequence[:-lag]) - mean) * (np.array(sequence[lag:]) - mean)) / var
    return corr


def gap_analysis(draws, n_balls=60):
    """Average gap between consecutive appearances of each ball."""
    last_seen = {}
    gaps = defaultdict(list)

    for i, draw in enumerate(draws):
        for b in draw:
            if b in last_seen:
                gaps[b].append(i - last_seen[b])
            last_seen[b] = i

    all_gaps = []
    for b in range(1, n_balls + 1):
        if gaps[b]:
            all_gaps.extend(gaps[b])

    if not all_gaps:
        return 0.0, 0.0

    return np.mean(all_gaps), np.std(all_gaps)


def sum_distribution(draws):
    """Statistics of the sum of 6 balls per draw."""
    sums = [sum(d) for d in draws]
    return np.mean(sums), np.std(sums), float(np.min(sums)), float(np.max(sums))


def consecutive_frequency(draws):
    """Fraction of draws containing at least one pair of consecutive numbers."""
    count = 0
    for draw in draws:
        has_consec = any(draw[i + 1] - draw[i] == 1 for i in range(len(draw) - 1))
        if has_consec:
            count += 1
    return count / len(draws)


def hot_cold_ratio(draws, window=50):
    """Ratio of 'hot' (above-average frequency) to 'cold' numbers in rolling windows."""
    if len(draws) < window:
        return 0.0

    ratios = []
    for i in range(window, len(draws)):
        recent = draws[i - window:i]
        counts = Counter()
        for d in recent:
            for b in d:
                counts[b] += 1

        expected = (window * 6) / 60  # expected frequency per ball
        hot = sum(1 for c in counts.values() if c > expected * 1.3)
        cold = sum(1 for b in range(1, 61) if counts.get(b, 0) < expected * 0.7)
        if cold > 0:
            ratios.append(hot / cold)

    return np.mean(ratios) if ratios else 0.0


def hurst_exponent(sequence):
    """Estimate Hurst exponent via R/S analysis."""
    seq = np.array(sequence, dtype=float)
    n = len(seq)
    if n < 20:
        return 0.5

    max_k = min(n // 4, 500)
    min_k = 10

    rs_values = []
    ns_values = []

    for k in range(min_k, max_k + 1, max(1, (max_k - min_k) // 20)):
        rs_list = []
        for start in range(0, n - k + 1, k):
            segment = seq[start:start + k]
            mean_seg = np.mean(segment)
            deviations = np.cumsum(segment - mean_seg)
            R = np.max(deviations) - np.min(deviations)
            S = np.std(segment, ddof=1)
            if S > 0:
                rs_list.append(R / S)

        if rs_list:
            rs_values.append(np.mean(rs_list))
            ns_values.append(k)

    if len(rs_values) < 3:
        return 0.5

    log_n = np.log(ns_values)
    log_rs = np.log(rs_values)

    # Linear regression
    coeffs = np.polyfit(log_n, log_rs, 1)
    return coeffs[0]


def runs_test(sequence):
    """Runs test — counts runs above/below median."""
    median = np.median(sequence)
    binary = [1 if x > median else 0 for x in sequence]

    runs = 1
    for i in range(1, len(binary)):
        if binary[i] != binary[i - 1]:
            runs += 1

    n1 = sum(binary)
    n0 = len(binary) - n1

    if n0 == 0 or n1 == 0:
        return 0.0

    # Expected runs and variance
    expected = (2 * n0 * n1) / (n0 + n1) + 1
    var = (2 * n0 * n1 * (2 * n0 * n1 - n0 - n1)) / ((n0 + n1) ** 2 * (n0 + n1 - 1))

    if var <= 0:
        return 0.0

    z = (runs - expected) / sqrt(var)
    return z


def birthday_spacing(draws):
    """Birthday spacing test — distribution of gaps between sorted ball values."""
    all_spacings = []
    for draw in draws:
        s = sorted(draw)
        spacings = [s[i + 1] - s[i] for i in range(len(s) - 1)]
        all_spacings.extend(spacings)

    return np.mean(all_spacings), np.std(all_spacings)


# ─── Flatten draws to sequences ─────────────────────────────────

def draws_to_sequence(draws):
    """Flatten list of draws into a single sequence of ball numbers."""
    return [b for draw in draws for b in draw]


def draws_to_sums(draws):
    """Convert draws to sequence of sums."""
    return [sum(d) for d in draws]


# ─── Main Analysis ──────────────────────────────────────────────

def analyze(draws, label):
    """Run all metrics on a set of draws."""
    seq = draws_to_sequence(draws)
    sums = draws_to_sums(draws)

    chi2 = frequency_chi_squared(draws)
    pe = permutation_entropy(seq, order=4)
    sc = serial_correlation(seq, lag=1)
    gap_mean, gap_std = gap_analysis(draws)
    sum_mean, sum_std, sum_min, sum_max = sum_distribution(draws)
    consec = consecutive_frequency(draws)
    hc = hot_cold_ratio(draws)
    hurst = hurst_exponent(sums)
    runs_z = runs_test(sums)
    bday_mean, bday_std = birthday_spacing(draws)

    results = {
        'Chi² (freq)': chi2,
        'Perm. Entropy (PE)': pe,
        'Serial Corr (lag-1)': sc,
        'Gap Mean': gap_mean,
        'Gap Std': gap_std,
        'Sum Mean': sum_mean,
        'Sum Std': sum_std,
        'Consecutive %': consec,
        'Hot/Cold Ratio': hc,
        'Hurst (sums)': hurst,
        'Runs Z (sums)': runs_z,
        'Birthday Mean': bday_mean,
        'Birthday Std': bday_std,
    }

    return results


def print_comparison(mega, crng_results, prng_results):
    """Print side-by-side comparison table."""
    print("\n" + "=" * 90)
    print(f"{'METRIC':<22} {'MEGA-SENA':>14} {'CRNG':>14} {'NumPy PRNG':>14} {'WINNER':>12}")
    print("=" * 90)

    crng_wins = 0
    prng_wins = 0

    for key in mega:
        m = mega[key]
        c = crng_results[key]
        p = prng_results[key]

        # Distance to Mega-Sena
        dist_c = abs(c - m)
        dist_p = abs(p - m)

        if dist_c < dist_p:
            winner = "✅ CRNG"
            crng_wins += 1
        elif dist_p < dist_c:
            winner = "❌ PRNG"
            prng_wins += 1
        else:
            winner = "🤝 TIE"

        print(f"  {key:<20} {m:>14.4f} {c:>14.4f} {p:>14.4f} {winner:>12}")

    total = len(mega)
    print("=" * 90)
    print(f"\n  CRNG wins: {crng_wins}/{total} ({100*crng_wins/total:.0f}%)")
    print(f"  PRNG wins: {prng_wins}/{total} ({100*prng_wins/total:.0f}%)")
    print(f"  Ties:      {total - crng_wins - prng_wins}/{total}")

    return crng_wins, prng_wins


def main():
    print("=" * 90)
    print("  MEGA-SENA vs CRNG vs NumPy PRNG — Statistical Fingerprint Analysis")
    print("=" * 90)

    # Load real data
    xlsx_path = '/Users/alebrotto/Deriv MCP/Mega-Sena.xlsx'
    print("\n📊 Loading Mega-Sena data...")
    mega_draws = load_mega_sena(xlsx_path)
    n = len(mega_draws)

    # Multi-seed analysis
    N_SEEDS = 10
    print(f"\n🎲 Generating {n} synthetic draws × {N_SEEDS} seeds...")

    all_crng_wins = 0
    all_prng_wins = 0
    all_total = 0

    # Accumulate results across seeds
    crng_accum = defaultdict(list)
    prng_accum = defaultdict(list)

    for seed in range(N_SEEDS):
        print(f"\n  Seed {seed}...")
        prng_draws = generate_prng_draws(n, seed=seed)
        crng_draws = generate_crng_draws(n, seed=seed)

        crng_res = analyze(crng_draws, f"CRNG(seed={seed})")
        prng_res = analyze(prng_draws, f"PRNG(seed={seed})")

        for k in crng_res:
            crng_accum[k].append(crng_res[k])
            prng_accum[k].append(prng_res[k])

    # Analyze real Mega-Sena
    print("\n📊 Analyzing Mega-Sena...")
    mega_res = analyze(mega_draws, "Mega-Sena")

    # Average across seeds
    crng_avg = {k: np.mean(v) for k, v in crng_accum.items()}
    prng_avg = {k: np.mean(v) for k, v in prng_accum.items()}

    print(f"\n  Analysis complete. {n} draws × 13 metrics × {N_SEEDS} seeds")

    # Print comparison
    crng_wins, prng_wins = print_comparison(mega_res, crng_avg, prng_avg)

    # ─── Detailed per-seed analysis ─────────────────────────────
    print("\n\n" + "=" * 90)
    print("  PER-SEED BREAKDOWN: How often does CRNG beat PRNG?")
    print("=" * 90)

    seed_crng_wins = []
    for seed in range(N_SEEDS):
        wins = 0
        total = len(mega_res)
        for i, k in enumerate(mega_res):
            m = mega_res[k]
            c = crng_accum[k][seed]
            p = prng_accum[k][seed]
            if abs(c - m) < abs(p - m):
                wins += 1
        seed_crng_wins.append(wins)
        print(f"  Seed {seed:2d}: CRNG wins {wins}/{total} ({100*wins/total:.0f}%)")

    avg_wins = np.mean(seed_crng_wins)
    print(f"\n  Average: CRNG wins {avg_wins:.1f}/{len(mega_res)} ({100*avg_wins/len(mega_res):.0f}%)")

    # ─── Key insight: PE comparison ─────────────────────────────
    print("\n\n" + "=" * 90)
    print("  KEY INSIGHT: Permutation Entropy (Ordinal Complexity)")
    print("=" * 90)

    print(f"\n  Mega-Sena PE:  {mega_res['Perm. Entropy (PE)']:.6f}")
    print(f"  CRNG avg PE:   {crng_avg['Perm. Entropy (PE)']:.6f}  (Δ = {abs(crng_avg['Perm. Entropy (PE)'] - mega_res['Perm. Entropy (PE)']):.6f})")
    print(f"  PRNG avg PE:   {prng_avg['Perm. Entropy (PE)']:.6f}  (Δ = {abs(prng_avg['Perm. Entropy (PE)'] - mega_res['Perm. Entropy (PE)']):.6f})")

    pe_crng_closer = abs(crng_avg['Perm. Entropy (PE)'] - mega_res['Perm. Entropy (PE)']) < abs(prng_avg['Perm. Entropy (PE)'] - mega_res['Perm. Entropy (PE)'])
    print(f"\n  → {'CRNG' if pe_crng_closer else 'PRNG'} is closer to Mega-Sena's ordinal complexity")

    # ─── Hurst comparison ───────────────────────────────────────
    print(f"\n  Mega-Sena Hurst:  {mega_res['Hurst (sums)']:.4f}")
    print(f"  CRNG avg Hurst:   {crng_avg['Hurst (sums)']:.4f}  (Δ = {abs(crng_avg['Hurst (sums)'] - mega_res['Hurst (sums)']):.4f})")
    print(f"  PRNG avg Hurst:   {prng_avg['Hurst (sums)']:.4f}  (Δ = {abs(prng_avg['Hurst (sums)'] - mega_res['Hurst (sums)']):.4f})")

    hurst_crng_closer = abs(crng_avg['Hurst (sums)'] - mega_res['Hurst (sums)']) < abs(prng_avg['Hurst (sums)'] - mega_res['Hurst (sums)'])
    print(f"\n  → {'CRNG' if hurst_crng_closer else 'PRNG'} is closer to Mega-Sena's memory structure")

    print("\n" + "=" * 90)
    print("  CONCLUSION")
    print("=" * 90)
    total_metrics = len(mega_res)
    print(f"\n  CRNG matches Mega-Sena better on {crng_wins}/{total_metrics} metrics ({100*crng_wins/total_metrics:.0f}%)")
    print(f"  across {N_SEEDS} seeds with {n} draws each.")

    if crng_wins > prng_wins:
        print(f"\n  🏆 CRNG captures real-world lottery statistical signatures")
        print(f"     that standard PRNGs miss.")
    elif prng_wins > crng_wins:
        print(f"\n  📊 PRNG is closer on more metrics — lottery may be truly uniform.")
    else:
        print(f"\n  🤝 It's a tie — both generators match Mega-Sena similarly.")

    print()


if __name__ == '__main__':
    main()
